import { Item } from '../../interfaces/item';

export const RANDOM_ITEMS: Item[] = [
  { name: 'Clean bedroom', status: false },
  { name: 'Learn python', status: false },
  { name: 'Cook dinner', status: false },
  { name: 'Read book', status: false },
  { name: 'Do laundry', status: false },
  { name: 'Call parents', status: false },
  { name: 'Run errand', status: false },
  { name: 'Go shopping', status: false },
  { name: 'Pay bills', status: false },
  { name: 'Take dog for walk', status: false },
  { name: 'Water Plants', status: false },
  { name: 'Go To Gym', status: false },
  { name: 'Meditate', status: false },
  { name: 'Write Blog Post', status: false },
  { name: 'Code Project', status: false },
  { name: 'Study For Test', status: false },
  { name: 'Plan Trip', status: false },
  { name: 'Organize Closet', status: false },
  { name: 'Clean Kitchen', status: false },
  { name: 'Repair Car', status: false },
  { name: 'Bake Cookies', status: false },
  { name: 'Clean Bathroom', status: false },
  { name: 'Mow Lawn', status: false },
  { name: 'Paint Wall', status: false },
  { name: 'Recolor Room', status: false },
  { name: 'Go Hiking', status: false },
  { name: 'Attend Meeting', status: false },
  { name: 'Take Photos', status: false },
  { name: 'Edit Video', status: false },
  { name: 'Clean Garage', status: false },
  { name: 'Shovel Snow', status: false },
  { name: 'Plant Garden', status: false },
  { name: 'Learn Guitar', status: false },
  { name: 'Cook Pasta', status: false },
  { name: 'Read Newspaper', status: false },
  { name: 'Call Friend', status: false },
  { name: 'Go Grocery Shopping', status: false },
  { name: 'Pay Rent', status: false },
  { name: 'Go To Doctor', status: false },
  { name: 'Go To Dentist', status: false },
  { name: 'Go To Therapy', status: false },
  { name: 'Go To Yoga', status: false },
  { name: 'Go To Concert', status: false },
  { name: 'Go To Movie', status: false },
  { name: 'Go To Art Gallery', status: false },
  { name: 'Go To Museum', status: false },
  { name: 'Go To Library', status: false },
  { name: 'Go To Park', status: false },
  { name: 'Go To Beach', status: false },
  { name: 'Go To Mountain', status: false },
  { name: 'Go To Forest', status: false },
  { name: 'Go To Desert', status: false },
  { name: 'Go To Jungle', status: false },
  { name: 'Go To Ocean', status: false },
  { name: 'Go To Space', status: false },
  { name: 'Go To Moon', status: false },
  { name: 'Go To Mars', status: false },
  { name: 'Go To Jupiter', status: false },
  { name: 'Go To Saturn', status: false },
  { name: 'Go To Uranus', status: false },
  { name: 'Go To Neptune', status: false },
  { name: 'Go To Pluto', status: false },
  { name: 'Go To Venus', status: false },
  { name: 'Go To Mercury', status: false },
  { name: 'Go To Earth', status: false },
];
