import { Item } from '../../interfaces/item';

export const RANDOM_ITEMS: Item[] = [
  { name: 'Study angular', status: 0 },
  { name: 'Fix item style', status: 0 },
  { name: 'Create list component', status: 0 },
  { name: 'Create item component', status: 0 },
  { name: 'Create service', status: 0 },
  { name: 'Create mock data', status: 0 },
  { name: 'Create list style', status: 0 },
  { name: 'Clean bedroom', status: 0 },
  { name: 'Learn python', status: 0 },
  { name: 'Cook dinner', status: 0 },
  { name: 'Read book', status: 0 },
  { name: 'Do laundry', status: 0 },
  { name: 'Call parents', status: 0 },
  { name: 'Run errand', status: 0 },
  { name: 'Go shopping', status: 0 },
  { name: 'Pay bills', status: 0 },
  { name: 'Take dog for walk', status: 0 },
  { name: 'Water Plants', status: 0 },
  { name: 'Go To Gym', status: 0 },
  { name: 'Meditate', status: 0 },
  { name: 'Write Blog Post', status: 0 },
  { name: 'Code Project', status: 0 },
  { name: 'Study For Test', status: 0 },
  { name: 'Plan Trip', status: 0 },
  { name: 'Organize Closet', status: 0 },
  { name: 'Clean Kitchen', status: 0 },
  { name: 'Repair Car', status: 0 },
  { name: 'Bake Cookies', status: 0 },
  { name: 'Clean Bathroom', status: 0 },
  { name: 'Mow Lawn', status: 0 },
  { name: 'Paint Wall', status: 0 },
  { name: 'Recolor Room', status: 0 },
  { name: 'Go Hiking', status: 0 },
  { name: 'Attend Meeting', status: 0 },
  { name: 'Take Photos', status: 0 },
  { name: 'Edit Video', status: 0 },
  { name: 'Clean Garage', status: 0 },
  { name: 'Shovel Snow', status: 0 },
  { name: 'Plant Garden', status: 0 },
  { name: 'Learn Guitar', status: 0 },
  { name: 'Cook Pasta', status: 0 },
  { name: 'Read Newspaper', status: 0 },
  { name: 'Call Friend', status: 0 },
  { name: 'Go Grocery Shopping', status: 0 },
  { name: 'Pay Rent', status: 0 },
  { name: 'Go To Doctor', status: 0 },
  { name: 'Go To Dentist', status: 0 },
  { name: 'Go To Therapy', status: 0 },
  { name: 'Go To Yoga', status: 0 },
  { name: 'Go To Concert', status: 0 },
  { name: 'Go To Movie', status: 0 },
  { name: 'Go To Art Gallery', status: 0 },
  { name: 'Go To Museum', status: 0 },
  { name: 'Go To Library', status: 0 },
  { name: 'Go To Park', status: 0 },
  { name: 'Go To Beach', status: 0 },
  { name: 'Go To Mountain', status: 0 },
  { name: 'Go To Forest', status: 0 },
  { name: 'Go To Desert', status: 0 },
  { name: 'Go To Jungle', status: 0 },
  { name: 'Go To Ocean', status: 0 },
  { name: 'Go To Space', status: 0 },
  { name: 'Go To Moon', status: 0 },
  { name: 'Go To Mars', status: 0 },
  { name: 'Go To Jupiter', status: 0 },
  { name: 'Go To Saturn', status: 0 },
  { name: 'Go To Uranus', status: 0 },
  { name: 'Go To Neptune', status: 0 },
  { name: 'Go To Pluto', status: 0 },
  { name: 'Go To Venus', status: 0 },
  { name: 'Go To Mercury', status: 0 },
  { name: 'Go To Earth', status: 0 },
];
