version: "3"
services:
  # image for Python (Flask 3.8) server
  python-app:
    build:
      context: .
      dockerfile: Dockerfilepython
    volumes:
      - ./python-api:/usr/src/app
    ports:
      - 8081:5000
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    volumes:
      - db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d # Mount the directory containing setup.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
    ports:
      - 8084:80
    depends_on:
      - db

volumes:
  db-data:
